### ISSUE TITLE
MAKE US AN 8 BALL COMMAND

### ISSUE THREAD

**Issue by wheetboi** [tonyrubak/rami2#2]
TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL TONY GIVE US 8 BALL

**Comment by tonyrubak** [comment]
Added in v0.2.2.
